In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [19]:
def fit(X_train , Y_train):
    result = {}
    result['total_data'] = len(Y_train)
    class_values = set(Y_train)
    for current_class in class_values:
        result[current_class] = {}
        current_class_rows = (Y_train == current_class)
        X_train_current = X_train[current_class_rows]
        Y_train_current = Y_train[current_class_rows]
        result[current_class]['total_count'] = len(Y_train_current) 
        for j in range(X_train.shape[1]):
            result[current_class][j] = {}
            all_possible_values = set(X_train[:,j])
            for current_value in all_possible_values:
                result[current_class][j][current_value] = (X_train_current[:,j] == current_value).sum()
    return result

In [20]:
# Using logarithmic probability
def probability(dictionary , x , current_class):
    output = np.log(dictionary[current_class]['total_count']) / np.log(dictionary['total_data'])
    num_features = x.shape[-1]
    for j in range(num_features):
        xj = x[j]
        count_current_class_with_value_xj = dictionary[current_class][j][xj] + 1
        count_current_class = dictionary[current_class]['total_count'] + len(dictionary[current_class][j].keys())
        current_xj_probability = np.log(count_current_class_with_value_xj) / np.log(count_current_class)
        output = output + current_xj_probability
    return output

In [21]:
def predictSinglePoint(dictionary , x):
    classes = dictionary.keys()
    best_p = -1000
    best_class = -1
    first_run = True
    for current_class in classes:
        if (current_class == 'total_data'):
            continue
        p_current_class = probability(dictionary , x , current_class)
        if(first_run or p_current_class > best_p):
            best_p = p_current_class
            best_class = current_class
        first_run = False
    return best_class

In [22]:
def predict(dictionary , X_test):
    Y_pred = []
    for x in X_test:
        x_class = predictSinglePoint(dictionary , x)
        Y_pred.append(x_class)
    return Y_pred

In [23]:

def makeLabelled(column):
    second_limit = column.mean()
    first_limit = second_limit * 0.5
    third_limit = second_limit * 1.5
    for i in range(0,len(column)):
        if(column[i] < first_limit):
            column[i] = 0
        elif(column[i] > first_limit and column[i] < second_limit):
            column[i] = 1
        elif(column[i] > second_limit  and column[i] < third_limit):
            column[i] = 2
        else:
            column[i] = 3
    return column

In [24]:
#Import Scikit-learn
from sklearn import naive_bayes
from sklearn.metrics import classification_report , confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target
for i in range(0 , X.shape[1]):
    X[: , i] = makeLabelled(X[: , i])

In [25]:
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , random_state = 0 , test_size = 0.25)
dictionary = fit(X_train , Y_train)
Y_pred = predict(dictionary , X_test)
matrix = confusion_matrix(Y_test , Y_pred)
report = classification_report(Y_test , Y_pred)

In [26]:
print(matrix)
print(report)

[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38



In [27]:
alg1 = naive_bayes.GaussianNB()
alg1.fit(X_train , Y_train)
Y_pred = alg1.predict(X_test)
print(confusion_matrix(Y_test , Y_pred))
print(classification_report(Y_test , Y_pred))

[[11  2  0]
 [ 0 16  0]
 [ 0  3  6]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.76      1.00      0.86        16
           2       1.00      0.67      0.80         9

    accuracy                           0.87        38
   macro avg       0.92      0.84      0.86        38
weighted avg       0.90      0.87      0.87        38



In [28]:
alg2 = naive_bayes.BernoulliNB()
alg2.fit(X_train , Y_train)
Y_pred = alg2.predict(X_test)
print(confusion_matrix(Y_test , Y_pred))
print(classification_report(Y_test , Y_pred))

[[11  0  2]
 [ 0  0 16]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.00      0.00      0.00        16
           2       0.33      1.00      0.50         9

    accuracy                           0.53        38
   macro avg       0.44      0.62      0.47        38
weighted avg       0.42      0.53      0.43        38



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
from sklearn import naive_bayes
alg3 = naive_bayes.MultinomialNB()
alg3.fit(X_train , Y_train)
Y_pred = alg3.predict(X_test)
print(confusion_matrix(Y_test , Y_pred))
print(classification_report(Y_test , Y_pred))

[[11  2  0]
 [ 0  0 16]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.00      0.00      0.00        16
           2       0.36      1.00      0.53         9

    accuracy                           0.53        38
   macro avg       0.45      0.62      0.48        38
weighted avg       0.43      0.53      0.44        38

